
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},q;for(q in g)g.hasOwnProperty(q)&&(aa[q]=g[q]);var ba=!1,x=!1,ca=!1,da=!1;ba="object"===typeof window;x="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!x;var y="",ea,fa,ha,ia;
if(ca)y=x?require("path").dirname(y)+"/":__dirname+"/",ea=function(a,b){ha||(ha=require("fs"));ia||(ia=require("path"));a=ia.normalize(a);return ha.readFileSync(a,b?null:"utf8")},fa=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",z),g.inspect=function(){return"[Emscripten Module object]"};
else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),fa=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||x)x?y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(y=document.currentScript.src),y=
0!==y.indexOf("blob:")?y.substr(0,y.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},x&&(fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ja=g.print||console.log.bind(console),A=g.printErr||console.warn.bind(console);for(q in aa)aa.hasOwnProperty(q)&&(g[q]=aa[q]);aa=null;var ka;g.wasmBinary&&(ka=g.wasmBinary);var noExitRuntime;
g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var la,ma=!1;function assert(a,b){a||z("Assertion failed: "+b)}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&na)return na.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function pa(a,b,c){var d=C;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function ra(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&sa[c];)++c;c<<=1;if(32<c-a&&qa)return qa.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function ua(a){return 2*a.length}
function va(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ya,za,C,D,sa,E,F,Aa,Ba,Ca,Da=[],Ea=[],Fa=[],Ga=[];function Ha(){var a=g.preRun.shift();Da.unshift(a)}var G=0,Ia=null,Ja=null;g.preloadedImages={};g.preloadedAudios={};function z(a){if(g.onAbort)g.onAbort(a);A(a);ma=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Ka(a){var b=H;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function La(){return Ka("data:application/octet-stream;base64,")}var H="kissfft.wasm";if(!La()){var Ma=H;H=g.locateFile?g.locateFile(Ma,y):y+Ma}function Na(){var a=H;try{if(a==H&&ka)return new Uint8Array(ka);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Oa(){return ka||!ba&&!x||"function"!==typeof fetch||Ka("file://")?Promise.resolve().then(function(){return Na()}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Na()})}function Pa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.na;"number"===typeof c?void 0===b.ga?Ca.get(c)():Ca.get(c)(b.ga):c(void 0===b.ga?null:b.ga)}}}
function Qa(a){this.O=a-16;this.Ba=function(b){E[this.O+8>>2]=b};this.ya=function(b){E[this.O+0>>2]=b};this.za=function(){E[this.O+4>>2]=0};this.xa=function(){za[this.O+12>>0]=0};this.Aa=function(){za[this.O+13>>0]=0};this.ra=function(b,c){this.Ba(b);this.ya(c);this.za();this.xa();this.Aa()}}var Ra=0;function Sa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ta=void 0;
function J(a){for(var b="";C[a];)b+=Ta[C[a++]];return b}var K={},L={},Ua={};function Va(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Wa(a,b){a=Va(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Xa(a){var b=Error,c=Wa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var M=void 0;function N(a){throw new M(a);}var Ya=void 0;function Za(a){throw new Ya(a);}
function $a(a,b,c){function d(h){h=c(h);h.length!==a.length&&Za("Mismatched type converter count");for(var m=0;m<a.length;++m)O(a[m],h[m])}a.forEach(function(h){Ua[h]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(h,m){L.hasOwnProperty(h)?e[m]=L[h]:(f.push(h),K.hasOwnProperty(h)||(K[h]=[]),K[h].push(function(){e[m]=L[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function O(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||N('type "'+d+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(a)){if(c.qa)return;N("Cannot register type '"+d+"' twice")}L[a]=b;delete Ua[a];K.hasOwnProperty(a)&&(b=K[a],delete K[a],b.forEach(function(e){e()}))}function ab(a){return{count:a.count,Z:a.Z,aa:a.aa,O:a.O,R:a.R,S:a.S,T:a.T}}
function bb(a){N(a.N.R.P.name+" instance already deleted")}var cb=!1;function db(){}function eb(a){--a.count.value;0===a.count.value&&(a.S?a.T.Y(a.S):a.R.P.Y(a.O))}function fb(a){if("undefined"===typeof FinalizationGroup)return fb=function(b){return b},a;cb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.O?eb(c):console.warn("object already deleted: "+c.O)});fb=function(b){cb.register(b,b.N,b.N);return b};db=function(b){cb.unregister(b.N)};return fb(a)}
var gb=void 0,hb=[];function ib(){for(;hb.length;){var a=hb.pop();a.N.Z=!1;a["delete"]()}}function P(){}var jb={};function kb(a,b,c){if(void 0===a[b].V){var d=a[b];a[b]=function(){a[b].V.hasOwnProperty(arguments.length)||N("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].V+")!");return a[b].V[arguments.length].apply(this,arguments)};a[b].V=[];a[b].V[d.da]=d}}
function lb(a,b){g.hasOwnProperty(a)?(N("Cannot register public name '"+a+"' twice"),kb(g,a,a),g.hasOwnProperty(void 0)&&N("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].V[void 0]=b):g[a]=b}function mb(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.$=c;this.Y=d;this.U=e;this.oa=f;this.ba=k;this.ma=h;this.ua=[]}
function nb(a,b,c){for(;b!==c;)b.ba||N("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ba(a),b=b.U;return a}function ob(a,b){if(null===b)return this.ha&&N("null is not a valid "+this.name),0;b.N||N('Cannot pass "'+S(b)+'" as a '+this.name);b.N.O||N("Cannot pass deleted object as a pointer of type "+this.name);return nb(b.N.O,b.N.R.P,this.P)}
function pb(a,b){if(null===b){this.ha&&N("null is not a valid "+this.name);if(this.fa){var c=this.va();null!==a&&a.push(this.Y,c);return c}return 0}b.N||N('Cannot pass "'+S(b)+'" as a '+this.name);b.N.O||N("Cannot pass deleted object as a pointer of type "+this.name);!this.ea&&b.N.R.ea&&N("Cannot convert argument of type "+(b.N.T?b.N.T.name:b.N.R.name)+" to parameter type "+this.name);c=nb(b.N.O,b.N.R.P,this.P);if(this.fa)switch(void 0===b.N.S&&N("Passing raw pointer to smart pointer is illegal"),
this.Ca){case 0:b.N.T===this?c=b.N.S:N("Cannot convert argument of type "+(b.N.T?b.N.T.name:b.N.R.name)+" to parameter type "+this.name);break;case 1:c=b.N.S;break;case 2:if(b.N.T===this)c=b.N.S;else{var d=b.clone();c=this.wa(c,T(function(){d["delete"]()}));null!==a&&a.push(this.Y,c)}break;default:N("Unsupporting sharing policy")}return c}
function qb(a,b){if(null===b)return this.ha&&N("null is not a valid "+this.name),0;b.N||N('Cannot pass "'+S(b)+'" as a '+this.name);b.N.O||N("Cannot pass deleted object as a pointer of type "+this.name);b.N.R.ea&&N("Cannot convert argument of type "+b.N.R.name+" to parameter type "+this.name);return nb(b.N.O,b.N.R.P,this.P)}function rb(a){return this.fromWireType(F[a>>2])}function sb(a,b,c){if(b===c)return a;if(void 0===c.U)return null;a=sb(a,b,c.U);return null===a?null:c.ma(a)}var tb={};
function ub(a,b){for(void 0===b&&N("ptr should not be undefined");a.U;)b=a.ba(b),a=a.U;return tb[b]}function vb(a,b){b.R&&b.O||Za("makeClassHandle requires ptr and ptrType");!!b.T!==!!b.S&&Za("Both smartPtrType and smartPtr must be specified");b.count={value:1};return fb(Object.create(a,{N:{value:b}}))}function U(a,b,c,d){this.name=a;this.P=b;this.ha=c;this.ea=d;this.fa=!1;this.Y=this.wa=this.va=this.ka=this.Ca=this.ta=void 0;void 0!==b.U?this.toWireType=pb:(this.toWireType=d?ob:qb,this.W=null)}
function wb(a,b){g.hasOwnProperty(a)||Za("Replacing nonexistant public symbol");g[a]=b;g[a].da=void 0}function zb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var e;-1!=a.indexOf("j")?e=c&&c.length?g["dynCall_"+a].apply(null,[b].concat(c)):g["dynCall_"+a].call(null,b):e=Ca.get(b).apply(null,c);return e}}
function V(a,b){a=J(a);var c=-1!=a.indexOf("j")?zb(a,b):Ca.get(b);"function"!==typeof c&&N("unknown function pointer with signature "+a+": "+b);return c}var Ab=void 0;function Bb(a){a=Cb(a);var b=J(a);W(a);return b}function Db(a,b){function c(f){e[f]||L[f]||(Ua[f]?Ua[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ab(a+": "+d.map(Bb).join([", "]));}function Eb(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function Fb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Gb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Wa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Hb=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ib(a){4<a&&0===--X[a].ia&&(X[a]=void 0,Hb.push(a))}
function T(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Hb.length?Hb.pop():X.length;X[b]={ia:1,value:a};return b}}function S(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Jb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Aa[c>>2])};case 3:return function(c){return this.fromWireType(Ba[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Kb(a,b,c){switch(b){case 0:return c?function(d){return za[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return sa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Lb(a){a||N("Cannot use deleted val. handle = "+a);return X[a].value}function Mb(a,b){var c=L[a];void 0===c&&N(b+" has unknown type "+Bb(a));return c}var Nb={};
function Ob(a){var b=Nb[a];return void 0===b?J(a):b}var Pb=[];function Qb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Rb(a){var b=Pb.length;Pb.push(a);return b}function Sb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Mb(E[(b>>2)+d],"parameter "+d);return c}for(var Tb={},Ub=[null,[],[]],Vb=Array(256),Wb=0;256>Wb;++Wb)Vb[Wb]=String.fromCharCode(Wb);Ta=Vb;M=g.BindingError=Xa("BindingError");Ya=g.InternalError=Xa("InternalError");
P.prototype.isAliasOf=function(a){if(!(this instanceof P&&a instanceof P))return!1;var b=this.N.R.P,c=this.N.O,d=a.N.R.P;for(a=a.N.O;b.U;)c=b.ba(c),b=b.U;for(;d.U;)a=d.ba(a),d=d.U;return b===d&&c===a};P.prototype.clone=function(){this.N.O||bb(this);if(this.N.aa)return this.N.count.value+=1,this;var a=fb(Object.create(Object.getPrototypeOf(this),{N:{value:ab(this.N)}}));a.N.count.value+=1;a.N.Z=!1;return a};
P.prototype["delete"]=function(){this.N.O||bb(this);this.N.Z&&!this.N.aa&&N("Object already scheduled for deletion");db(this);eb(this.N);this.N.aa||(this.N.S=void 0,this.N.O=void 0)};P.prototype.isDeleted=function(){return!this.N.O};P.prototype.deleteLater=function(){this.N.O||bb(this);this.N.Z&&!this.N.aa&&N("Object already scheduled for deletion");hb.push(this);1===hb.length&&gb&&gb(ib);this.N.Z=!0;return this};U.prototype.pa=function(a){this.ka&&(a=this.ka(a));return a};
U.prototype.ja=function(a){this.Y&&this.Y(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=rb;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.fa?vb(this.P.$,{R:this.ta,O:c,T:this,S:a}):vb(this.P.$,{R:this,O:a})}var c=this.pa(a);if(!c)return this.ja(a),null;var d=ub(this.P,c);if(void 0!==d){if(0===d.N.count.value)return d.N.O=c,d.N.S=a,d.clone();d=d.clone();this.ja(a);return d}d=this.P.oa(c);d=jb[d];if(!d)return b.call(this);d=this.ea?d.la:d.pointerType;var e=sb(c,this.P,d.P);return null===e?b.call(this):this.fa?vb(d.P.$,{R:d,O:e,T:this,S:a}):vb(d.P.$,{R:d,O:e})};
g.getInheritedInstanceCount=function(){return Object.keys(tb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in tb)tb.hasOwnProperty(b)&&a.push(tb[b]);return a};g.flushPendingDeletes=ib;g.setDelayFunction=function(a){gb=a;hb.length&&gb&&gb(ib)};Ab=g.UnboundTypeError=Xa("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};Ea.push({na:function(){Xb()}});
var Zb={z:function(a){return Yb(a+16)+16},y:function(a,b,c){(new Qa(a)).ra(b,c);Ra++;throw a;},w:function(a,b,c,d,e){var f=Sa(c);b=J(b);O(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=za;else if(2===c)h=D;else if(4===c)h=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>f])},W:null})},h:function(a,b,c,d,e,f,k,h,m,l,n,t,u){n=J(n);f=V(e,f);h&&(h=V(k,h));l&&
(l=V(m,l));u=V(t,u);var B=Va(n);lb(B,function(){Db("Cannot construct "+n+" due to unbound types",[d])});$a([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var v=r.P;var p=v.$}else p=P.prototype;r=Wa(B,function(){if(Object.getPrototypeOf(this)!==I)throw new M("Use 'new' to construct "+n);if(void 0===w.X)throw new M(n+" has no accessible constructor");var Q=w.X[arguments.length];if(void 0===Q)throw new M("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+
Object.keys(w.X).toString()+") parameters instead!");return Q.apply(this,arguments)});var I=Object.create(p,{constructor:{value:r}});r.prototype=I;var w=new mb(n,r,I,u,v,f,h,l);v=new U(n,w,!0,!1);p=new U(n+"*",w,!1,!1);var Y=new U(n+" const*",w,!1,!0);jb[a]={pointerType:p,la:Y};wb(B,r);return[v,p,Y]})},g:function(a,b,c,d,e,f){assert(0<b);var k=Eb(b,c);e=V(d,e);var h=[f],m=[];$a([],[a],function(l){l=l[0];var n="constructor "+l.name;void 0===l.P.X&&(l.P.X=[]);if(void 0!==l.P.X[b-1])throw new M("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.P.X[b-1]=function(){Db("Cannot construct "+l.name+" due to unbound types",k)};$a([],k,function(t){l.P.X[b-1]=function(){arguments.length!==b-1&&N(n+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;h.length=b;for(var u=1;u<b;++u)h[u]=t[u].toWireType(m,arguments[u-1]);u=e.apply(null,h);Fb(m);return t[0].fromWireType(u)};return[]});return[]})},
d:function(a,b,c,d,e,f,k,h){var m=Eb(c,d);b=J(b);f=V(e,f);$a([],[a],function(l){function n(){Db("Cannot call "+t+" due to unbound types",m)}l=l[0];var t=l.name+"."+b;h&&l.P.ua.push(b);var u=l.P.$,B=u[b];void 0===B||void 0===B.V&&B.className!==l.name&&B.da===c-2?(n.da=c-2,n.className=l.name,u[b]=n):(kb(u,b,t),u[b].V[c-2]=n);$a([],m,function(r){var v=t,p=l,I=f,w=r.length;2>w&&N("argTypes array size mismatch! Must at least get return value and 'this' types!");var Y=null!==r[1]&&null!==p,Q=!1;for(p=1;p<
r.length;++p)if(null!==r[p]&&void 0===r[p].W){Q=!0;break}var xb="void"!==r[0].name,R="",Z="";for(p=0;p<w-2;++p)R+=(0!==p?", ":"")+"arg"+p,Z+=(0!==p?", ":"")+"arg"+p+"Wired";v="return function "+Va(v)+"("+R+") {\nif (arguments.length !== "+(w-2)+") {\nthrowBindingError('function "+v+" called with ' + arguments.length + ' arguments, expected "+(w-2)+" args!');\n}\n";Q&&(v+="var destructors = [];\n");var yb=Q?"destructors":"null";R="throwBindingError invoker fn runDestructors retType classParam".split(" ");
I=[N,I,k,Fb,r[0],r[1]];Y&&(v+="var thisWired = classParam.toWireType("+yb+", this);\n");for(p=0;p<w-2;++p)v+="var arg"+p+"Wired = argType"+p+".toWireType("+yb+", arg"+p+"); // "+r[p+2].name+"\n",R.push("argType"+p),I.push(r[p+2]);Y&&(Z="thisWired"+(0<Z.length?", ":"")+Z);v+=(xb?"var rv = ":"")+"invoker(fn"+(0<Z.length?", ":"")+Z+");\n";if(Q)v+="runDestructors(destructors);\n";else for(p=Y?1:2;p<r.length;++p)w=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==r[p].W&&(v+=w+"_dtor("+w+"); // "+r[p].name+
"\n",R.push(w+"_dtor"),I.push(r[p].W));xb&&(v+="var ret = retType.fromWireType(rv);\nreturn ret;\n");R.push(v+"}\n");r=Gb(R).apply(null,I);void 0===u[b].V?(r.da=c-2,u[b]=r):u[b].V[c-2]=r;return[]});return[]})},u:function(a,b){b=J(b);O(a,{name:b,fromWireType:function(c){var d=X[c].value;Ib(c);return d},toWireType:function(c,d){return T(d)},argPackAdvance:8,readValueFromPointer:rb,W:null})},m:function(a,b,c){c=Sa(c);b=J(b);O(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==
typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+S(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Jb(b,c),W:null})},b:function(a,b,c,d,e){function f(l){return l}b=J(b);-1===e&&(e=4294967295);var k=Sa(c);if(0===d){var h=32-8*c;f=function(l){return l<<h>>>h}}var m=-1!=b.indexOf("unsigned");O(a,{name:b,fromWireType:f,toWireType:function(l,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+S(n)+'" to '+this.name);if(n<d||
n>e)throw new TypeError('Passing a number "'+S(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Kb(b,k,0!==d),W:null})},a:function(a,b,c){function d(f){f>>=2;var k=F;return new e(ya,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=J(c);O(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{qa:!0})},
n:function(a,b){b=J(b);var c="std::string"===b;O(a,{name:b,fromWireType:function(d){var e=F[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var h=d+4+k;if(k==e||0==C[h]){f=f?oa(C,f,h-f):"";if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=h+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(C[d+4+k]);m=m.join("")}W(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof
Int8Array||N("Cannot pass non-string to std::string");var k=(c&&f?function(){for(var l=0,n=0;n<e.length;++n){var t=e.charCodeAt(n);55296<=t&&57343>=t&&(t=65536+((t&1023)<<10)|e.charCodeAt(++n)&1023);127>=t?++l:l=2047>=t?l+2:65535>=t?l+3:l+4}return l}:function(){return e.length})(),h=Yb(4+k+1);F[h>>2]=k;if(c&&f)pa(e,h+4,k+1);else if(f)for(f=0;f<k;++f){var m=e.charCodeAt(f);255<m&&(W(h),N("String has UTF-16 code units that do not fit in 8 bits"));C[h+4+f]=m}else for(f=0;f<k;++f)C[h+4+f]=e[f];null!==
d&&d.push(W,h);return h},argPackAdvance:8,readValueFromPointer:rb,W:function(d){W(d)}})},i:function(a,b,c){c=J(c);if(2===b){var d=ra;var e=ta;var f=ua;var k=function(){return sa};var h=1}else 4===b&&(d=va,e=wa,f=xa,k=function(){return F},h=2);O(a,{name:c,fromWireType:function(m){for(var l=F[m>>2],n=k(),t,u=m+4,B=0;B<=l;++B){var r=m+4+B*b;if(B==l||0==n[r>>h])u=d(u,r-u),void 0===t?t=u:(t+=String.fromCharCode(0),t+=u),u=r+b}W(m);return t},toWireType:function(m,l){"string"!==typeof l&&N("Cannot pass non-string to C++ string type "+
c);var n=f(l),t=Yb(4+n+b);F[t>>2]=n>>h;e(l,t+4,n+b);null!==m&&m.push(W,t);return t},argPackAdvance:8,readValueFromPointer:rb,W:function(m){W(m)}})},x:function(a,b){b=J(b);O(a,{sa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},B:function(a,b,c){a=Lb(a);b=Mb(b,"emval::as");var d=[],e=T(d);E[c>>2]=e;return b.toWireType(d,a)},j:function(a,b,c,d){a=Pb[a];b=Lb(b);c=Ob(c);a(b,c,null,d)},c:Ib,E:function(a){if(0===a)return T(Qb());a=Ob(a);return T(Qb()[a])},k:function(a,b){b=
Sb(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(l){return l.name}).join("_")+"$",e=["retType"],f=[c],k="",h=0;h<a-1;++h)k+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(b[1+h]);d="return function "+Va("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(h=0;h<a-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[h+1].argPackAdvance;d+="    var rv = handle[name]("+k+");\n";for(h=0;h<a-1;++h)b[h+1].deleteObject&&(d+="    argType"+
h+".deleteObject(arg"+h+");\n");c.sa||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Gb(e).apply(null,f);return Rb(a)},C:function(a,b){a=Lb(a);b=Lb(b);return T(a[b])},f:function(a){4<a&&(X[a].ia+=1)},v:function(a,b,c,d){a=Lb(a);var e=Tb[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)k+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Mb,g,T);Tb[b]=e}return e(a,c,d)},D:function(a){return T(Ob(a))},A:function(a){Fb(X[a].value);Ib(a)},e:function(a,b){a=Mb(a,"_emval_take_value");a=a.readValueFromPointer(b);return T(a)},s:function(){z()},q:function(a,b,c){C.copyWithin(a,
b,b+c)},r:function(){z("OOM")},t:function(){return 0},o:function(){},l:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var k=E[b+8*f>>2],h=E[b+(8*f+4)>>2],m=0;m<h;m++){var l=C[k+m],n=Ub[a];0===l||10===l?((1===a?ja:A)(oa(n,0)),n.length=0):n.push(l)}e+=h}E[d>>2]=e;return 0},p:function(){}};
(function(){function a(e){g.asm=e.exports;la=g.asm.F;ya=e=la.buffer;g.HEAP8=za=new Int8Array(e);g.HEAP16=D=new Int16Array(e);g.HEAP32=E=new Int32Array(e);g.HEAPU8=C=new Uint8Array(e);g.HEAPU16=sa=new Uint16Array(e);g.HEAPU32=F=new Uint32Array(e);g.HEAPF32=Aa=new Float32Array(e);g.HEAPF64=Ba=new Float64Array(e);Ca=g.asm.G;G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);0==G&&(null!==Ia&&(clearInterval(Ia),Ia=null),Ja&&(e=Ja,Ja=null,e()))}function b(e){a(e.instance)}function c(e){return Oa().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){A("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:Zb};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ka||"function"!==typeof WebAssembly.instantiateStreaming||La()||Ka("file://")||"function"!==typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){A("wasm streaming compile failed: "+f);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Xb=g.___wasm_call_ctors=function(){return(Xb=g.___wasm_call_ctors=g.asm.H).apply(null,arguments)},Yb=g._malloc=function(){return(Yb=g._malloc=g.asm.I).apply(null,arguments)},W=g._free=function(){return(W=g._free=g.asm.J).apply(null,arguments)},Cb=g.___getTypeName=function(){return(Cb=g.___getTypeName=g.asm.K).apply(null,arguments)};
g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.L).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.M).apply(null,arguments)};var $b;Ja=function ac(){$b||bc();$b||(Ja=ac)};
function bc(){function a(){if(!$b&&($b=!0,g.calledRun=!0,!ma)){Pa(Ea);Pa(Fa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ga.unshift(b)}Pa(Ga)}}if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ha();Pa(Da);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
g.run=bc;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();noExitRuntime=!0;bc();
