
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},t;for(t in g)g.hasOwnProperty(t)&&(aa[t]=g[t]);var ba=!1,y=!1,ca=!1,da=!1;ba="object"===typeof window;y="function"===typeof importScripts;ca="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;da=!ba&&!ca&&!y;var z="",ea,fa,ha,ia,ja;
if(ca)z=y?require("path").dirname(z)+"/":__dirname+"/",ea=function(a,b){ia||(ia=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);return ia.readFileSync(a,b?null:"utf8")},ha=function(a){a=ea(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",A),g.inspect=function(){return"[Emscripten Module object]"};
else if(da)"undefined"!=typeof read&&(ea=function(a){return read(a)}),ha=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||y)y?z=self.location.href:"undefined"!==typeof document&&document.currentScript&&(z=document.currentScript.src),z=
0!==z.indexOf("blob:")?z.substr(0,z.lastIndexOf("/")+1):"",ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};g.print||console.log.bind(console);
var ka=g.printErr||console.warn.bind(console);for(t in aa)aa.hasOwnProperty(t)&&(g[t]=aa[t]);aa=null;var la;g.wasmBinary&&(la=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&A("no native wasm support detected");var ma,na=!1;function assert(a,b){a||A("Assertion failed: "+b)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(a,b,c){var d=C;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var m=a.charCodeAt(++e);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function ra(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&sa[c];)++c;c<<=1;if(32<c-a&&qa)return qa.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function ua(a){return 2*a.length}
function va(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var m=a.charCodeAt(++e);f=65536+((f&1023)<<10)|m&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ya,za,C,D,sa,E,F,Aa,Ba;function Ca(){var a=ma.buffer;ya=a;g.HEAP8=za=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=sa=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=Aa=new Float32Array(a);g.HEAPF64=Ba=new Float64Array(a)}var Da,Ea=[],Fa=[],Ga=[],Ha=[];Fa.push({ha:function(){Ia()}});
function Ja(){var a=g.preRun.shift();Ea.unshift(a)}var G=0,Ka=null,La=null;g.preloadedImages={};g.preloadedAudios={};function A(a){if(g.onAbort)g.onAbort(a);ka(a);na=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ma(a){var b=H;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Na(){return Ma("data:application/octet-stream;base64,")}var H="jpeg.wasm";if(!Na()){var Oa=H;H=g.locateFile?g.locateFile(Oa,z):z+Oa}
function Pa(){var a=H;try{if(a==H&&la)return new Uint8Array(la);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Qa(){if(!la&&(ba||y)){if("function"===typeof fetch&&!Ma("file://"))return fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Pa()});if(fa)return new Promise(function(a,b){fa(H,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Pa()})}
function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ha;"number"===typeof c?void 0===b.$?Da.get(c)():Da.get(c)(b.$):c(void 0===b.$?null:b.$)}}}function Sa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ta=void 0;function I(a){for(var b="";C[a];)b+=Ta[C[a++]];return b}var J={},L={},Ua={};
function Va(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Wa(a,b){a=Va(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Xa(a){var b=Error,c=Wa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var M=void 0;function N(a){throw new M(a);}var Ya=void 0;function Za(a){throw new Ya(a);}
function O(a,b,c){function d(h){h=c(h);h.length!==a.length&&Za("Mismatched type converter count");for(var k=0;k<a.length;++k)P(a[k],h[k])}a.forEach(function(h){Ua[h]=b});var e=Array(b.length),f=[],m=0;b.forEach(function(h,k){L.hasOwnProperty(h)?e[k]=L[h]:(f.push(h),J.hasOwnProperty(h)||(J[h]=[]),J[h].push(function(){e[k]=L[h];++m;m===f.length&&d(e)}))});0===f.length&&d(e)}
function P(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||N('type "'+d+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(a)){if(c.ka)return;N("Cannot register type '"+d+"' twice")}L[a]=b;delete Ua[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(function(e){e()}))}function $a(a){return{count:a.count,U:a.U,V:a.V,J:a.J,K:a.K,L:a.L,M:a.M}}
function ab(a){N(a.H.K.I.name+" instance already deleted")}var bb=!1;function cb(){}function db(a){--a.count.value;0===a.count.value&&(a.L?a.M.T(a.L):a.K.I.T(a.J))}function eb(a){if("undefined"===typeof FinalizationGroup)return eb=function(b){return b},a;bb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.J?db(c):console.warn("object already deleted: "+c.J)});eb=function(b){bb.register(b,b.H,b.H);return b};cb=function(b){bb.unregister(b.H)};return eb(a)}
var fb=void 0,gb=[];function hb(){for(;gb.length;){var a=gb.pop();a.H.U=!1;a["delete"]()}}function Q(){}var ib={};function jb(a,b,c){if(void 0===a[b].O){var d=a[b];a[b]=function(){a[b].O.hasOwnProperty(arguments.length)||N("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].O+")!");return a[b].O[arguments.length].apply(this,arguments)};a[b].O=[];a[b].O[d.X]=d}}
function kb(a,b){g.hasOwnProperty(a)?(N("Cannot register public name '"+a+"' twice"),jb(g,a,a),g.hasOwnProperty(void 0)&&N("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].O[void 0]=b):g[a]=b}function lb(a,b,c,d,e,f,m,h){this.name=a;this.constructor=b;this.R=c;this.T=d;this.N=e;this.ia=f;this.W=m;this.ga=h;this.na=[]}
function mb(a,b,c){for(;b!==c;)b.W||N("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.W(a),b=b.N;return a}function nb(a,b){if(null===b)return this.aa&&N("null is not a valid "+this.name),0;b.H||N('Cannot pass "'+R(b)+'" as a '+this.name);b.H.J||N("Cannot pass deleted object as a pointer of type "+this.name);return mb(b.H.J,b.H.K.I,this.I)}
function ob(a,b){if(null===b){this.aa&&N("null is not a valid "+this.name);if(this.Z){var c=this.oa();null!==a&&a.push(this.T,c);return c}return 0}b.H||N('Cannot pass "'+R(b)+'" as a '+this.name);b.H.J||N("Cannot pass deleted object as a pointer of type "+this.name);!this.Y&&b.H.K.Y&&N("Cannot convert argument of type "+(b.H.M?b.H.M.name:b.H.K.name)+" to parameter type "+this.name);c=mb(b.H.J,b.H.K.I,this.I);if(this.Z)switch(void 0===b.H.L&&N("Passing raw pointer to smart pointer is illegal"),this.qa){case 0:b.H.M===
this?c=b.H.L:N("Cannot convert argument of type "+(b.H.M?b.H.M.name:b.H.K.name)+" to parameter type "+this.name);break;case 1:c=b.H.L;break;case 2:if(b.H.M===this)c=b.H.L;else{var d=b.clone();c=this.pa(c,U(function(){d["delete"]()}));null!==a&&a.push(this.T,c)}break;default:N("Unsupporting sharing policy")}return c}
function pb(a,b){if(null===b)return this.aa&&N("null is not a valid "+this.name),0;b.H||N('Cannot pass "'+R(b)+'" as a '+this.name);b.H.J||N("Cannot pass deleted object as a pointer of type "+this.name);b.H.K.Y&&N("Cannot convert argument of type "+b.H.K.name+" to parameter type "+this.name);return mb(b.H.J,b.H.K.I,this.I)}function qb(a){return this.fromWireType(F[a>>2])}function rb(a,b,c){if(b===c)return a;if(void 0===c.N)return null;a=rb(a,b,c.N);return null===a?null:c.ga(a)}var sb={};
function tb(a,b){for(void 0===b&&N("ptr should not be undefined");a.N;)b=a.W(b),a=a.N;return sb[b]}function ub(a,b){b.K&&b.J||Za("makeClassHandle requires ptr and ptrType");!!b.M!==!!b.L&&Za("Both smartPtrType and smartPtr must be specified");b.count={value:1};return eb(Object.create(a,{H:{value:b}}))}function V(a,b,c,d){this.name=a;this.I=b;this.aa=c;this.Y=d;this.Z=!1;this.T=this.pa=this.oa=this.ea=this.qa=this.ma=void 0;void 0!==b.N?this.toWireType=ob:(this.toWireType=d?nb:pb,this.P=null)}
function vb(a,b){g.hasOwnProperty(a)||Za("Replacing nonexistant public symbol");g[a]=b;g[a].X=void 0}function wb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=Da.get(b).apply(null,c);return d}}
function W(a,b){a=I(a);var c=-1!=a.indexOf("j")?wb(a,b):Da.get(b);"function"!==typeof c&&N("unknown function pointer with signature "+a+": "+b);return c}var xb=void 0;function yb(a){a=Bb(a);var b=I(a);X(a);return b}function Cb(a,b){function c(f){e[f]||L[f]||(Ua[f]?Ua[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new xb(a+": "+d.map(yb).join([", "]));}function Db(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function Eb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Fb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Wa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Gb(a,b,c){a instanceof Object||N(c+' with invalid "this": '+a);a instanceof b.I.constructor||N(c+' incompatible with "this" of type '+a.constructor.name);a.H.J||N("cannot call emscripten binding method "+c+" on deleted object");return mb(a.H.J,a.H.K.I,b.I)}var Hb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ib(a){4<a&&0===--Y[a].ba&&(Y[a]=void 0,Hb.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Hb.length?Hb.pop():Y.length;Y[b]={ba:1,value:a};return b}}function R(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Jb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Aa[c>>2])};case 3:return function(c){return this.fromWireType(Ba[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Kb(a,b,c){switch(b){case 0:return c?function(d){return za[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return sa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Lb(a){a||N("Cannot use deleted val. handle = "+a);return Y[a].value}function Mb(a,b){var c=L[a];void 0===c&&N(b+" has unknown type "+yb(a));return c}var Nb={};
function Ob(a){var b=Nb[a];return void 0===b?I(a):b}var Pb=[];function Qb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Rb(a){var b=Pb.length;Pb.push(a);return b}function Sb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Mb(E[(b>>2)+d],"parameter "+d);return c}for(var Tb={},Ub=Array(256),Vb=0;256>Vb;++Vb)Ub[Vb]=String.fromCharCode(Vb);Ta=Ub;M=g.BindingError=Xa("BindingError");Ya=g.InternalError=Xa("InternalError");
Q.prototype.isAliasOf=function(a){if(!(this instanceof Q&&a instanceof Q))return!1;var b=this.H.K.I,c=this.H.J,d=a.H.K.I;for(a=a.H.J;b.N;)c=b.W(c),b=b.N;for(;d.N;)a=d.W(a),d=d.N;return b===d&&c===a};Q.prototype.clone=function(){this.H.J||ab(this);if(this.H.V)return this.H.count.value+=1,this;var a=eb(Object.create(Object.getPrototypeOf(this),{H:{value:$a(this.H)}}));a.H.count.value+=1;a.H.U=!1;return a};
Q.prototype["delete"]=function(){this.H.J||ab(this);this.H.U&&!this.H.V&&N("Object already scheduled for deletion");cb(this);db(this.H);this.H.V||(this.H.L=void 0,this.H.J=void 0)};Q.prototype.isDeleted=function(){return!this.H.J};Q.prototype.deleteLater=function(){this.H.J||ab(this);this.H.U&&!this.H.V&&N("Object already scheduled for deletion");gb.push(this);1===gb.length&&fb&&fb(hb);this.H.U=!0;return this};V.prototype.ja=function(a){this.ea&&(a=this.ea(a));return a};
V.prototype.da=function(a){this.T&&this.T(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=qb;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.Z?ub(this.I.R,{K:this.ma,J:c,M:this,L:a}):ub(this.I.R,{K:this,J:a})}var c=this.ja(a);if(!c)return this.da(a),null;var d=tb(this.I,c);if(void 0!==d){if(0===d.H.count.value)return d.H.J=c,d.H.L=a,d.clone();d=d.clone();this.da(a);return d}d=this.I.ia(c);d=ib[d];if(!d)return b.call(this);d=this.Y?d.fa:d.pointerType;var e=rb(c,this.I,d.I);return null===e?b.call(this):this.Z?ub(d.I.R,{K:d,J:e,M:this,L:a}):ub(d.I.R,{K:d,J:e})};
g.getInheritedInstanceCount=function(){return Object.keys(sb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in sb)sb.hasOwnProperty(b)&&a.push(sb[b]);return a};g.flushPendingDeletes=hb;g.setDelayFunction=function(a){fb=a;gb.length&&fb&&fb(hb)};xb=g.UnboundTypeError=Xa("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};
var Xb={s:function(a,b,c,d,e){var f=Sa(c);b=I(b);P(a,{name:b,fromWireType:function(m){return!!m},toWireType:function(m,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(m){if(1===c)var h=za;else if(2===c)h=D;else if(4===c)h=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[m>>f])},P:null})},z:function(a,b,c,d,e,f,m,h,k,l,n,p,u){n=I(n);f=W(e,f);h&&(h=W(m,h));l&&(l=W(k,l));u=W(p,u);var v=Va(n);kb(v,function(){Cb("Cannot construct "+n+" due to unbound types",
[d])});O([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var w=q.I;var r=w.R}else r=Q.prototype;q=Wa(v,function(){if(Object.getPrototypeOf(this)!==B)throw new M("Use 'new' to construct "+n);if(void 0===x.S)throw new M(n+" has no accessible constructor");var S=x.S[arguments.length];if(void 0===S)throw new M("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(x.S).toString()+") parameters instead!");return S.apply(this,arguments)});var B=Object.create(r,
{constructor:{value:q}});q.prototype=B;var x=new lb(n,q,B,u,w,f,h,l);w=new V(n,x,!0,!1);r=new V(n+"*",x,!1,!1);var K=new V(n+" const*",x,!1,!0);ib[a]={pointerType:r,fa:K};vb(v,q);return[w,r,K]})},y:function(a,b,c,d,e,f){assert(0<b);var m=Db(b,c);e=W(d,e);var h=[f],k=[];O([],[a],function(l){l=l[0];var n="constructor "+l.name;void 0===l.I.S&&(l.I.S=[]);if(void 0!==l.I.S[b-1])throw new M("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
l.I.S[b-1]=function(){Cb("Cannot construct "+l.name+" due to unbound types",m)};O([],m,function(p){l.I.S[b-1]=function(){arguments.length!==b-1&&N(n+" called with "+arguments.length+" arguments, expected "+(b-1));k.length=0;h.length=b;for(var u=1;u<b;++u)h[u]=p[u].toWireType(k,arguments[u-1]);u=e.apply(null,h);Eb(k);return p[0].fromWireType(u)};return[]});return[]})},q:function(a,b,c,d,e,f,m,h){var k=Db(c,d);b=I(b);f=W(e,f);O([],[a],function(l){function n(){Cb("Cannot call "+p+" due to unbound types",
k)}l=l[0];var p=l.name+"."+b;h&&l.I.na.push(b);var u=l.I.R,v=u[b];void 0===v||void 0===v.O&&v.className!==l.name&&v.X===c-2?(n.X=c-2,n.className=l.name,u[b]=n):(jb(u,b,p),u[b].O[c-2]=n);O([],k,function(q){var w=p,r=l,B=f,x=q.length;2>x&&N("argTypes array size mismatch! Must at least get return value and 'this' types!");var K=null!==q[1]&&null!==r,S=!1;for(r=1;r<q.length;++r)if(null!==q[r]&&void 0===q[r].P){S=!0;break}var zb="void"!==q[0].name,T="",Z="";for(r=0;r<x-2;++r)T+=(0!==r?", ":"")+"arg"+r,
Z+=(0!==r?", ":"")+"arg"+r+"Wired";w="return function "+Va(w)+"("+T+") {\nif (arguments.length !== "+(x-2)+") {\nthrowBindingError('function "+w+" called with ' + arguments.length + ' arguments, expected "+(x-2)+" args!');\n}\n";S&&(w+="var destructors = [];\n");var Ab=S?"destructors":"null";T="throwBindingError invoker fn runDestructors retType classParam".split(" ");B=[N,B,m,Eb,q[0],q[1]];K&&(w+="var thisWired = classParam.toWireType("+Ab+", this);\n");for(r=0;r<x-2;++r)w+="var arg"+r+"Wired = argType"+
r+".toWireType("+Ab+", arg"+r+"); // "+q[r+2].name+"\n",T.push("argType"+r),B.push(q[r+2]);K&&(Z="thisWired"+(0<Z.length?", ":"")+Z);w+=(zb?"var rv = ":"")+"invoker(fn"+(0<Z.length?", ":"")+Z+");\n";if(S)w+="runDestructors(destructors);\n";else for(r=K?1:2;r<q.length;++r)x=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==q[r].P&&(w+=x+"_dtor("+x+"); // "+q[r].name+"\n",T.push(x+"_dtor"),B.push(q[r].P));zb&&(w+="var ret = retType.fromWireType(rv);\nreturn ret;\n");T.push(w+"}\n");q=Fb(T).apply(null,B);
void 0===u[b].O?(q.X=c-2,u[b]=q):u[b].O[c-2]=q;return[]});return[]})},e:function(a,b,c,d,e,f,m,h,k,l){b=I(b);e=W(d,e);O([],[a],function(n){n=n[0];var p=n.name+"."+b,u={get:function(){Cb("Cannot access "+p+" due to unbound types",[c,m])},enumerable:!0,configurable:!0};k?u.set=function(){Cb("Cannot access "+p+" due to unbound types",[c,m])}:u.set=function(){N(p+" is a read-only property")};Object.defineProperty(n.I.R,b,u);O([],k?[c,m]:[c],function(v){var q=v[0],w={get:function(){var B=Gb(this,n,p+" getter");
return q.fromWireType(e(f,B))},enumerable:!0};if(k){k=W(h,k);var r=v[1];w.set=function(B){var x=Gb(this,n,p+" setter"),K=[];k(l,x,r.toWireType(K,B));Eb(K)}}Object.defineProperty(n.I.R,b,w);return[]});return[]})},r:function(a,b){b=I(b);P(a,{name:b,fromWireType:function(c){var d=Y[c].value;Ib(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:qb,P:null})},h:function(a,b,c){c=Sa(c);b=I(b);P(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==
typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+R(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Jb(b,c),P:null})},b:function(a,b,c,d,e){function f(l){return l}b=I(b);-1===e&&(e=4294967295);var m=Sa(c);if(0===d){var h=32-8*c;f=function(l){return l<<h>>>h}}var k=-1!=b.indexOf("unsigned");P(a,{name:b,fromWireType:f,toWireType:function(l,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+R(n)+'" to '+this.name);if(n<d||
n>e)throw new TypeError('Passing a number "'+R(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return k?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Kb(b,m,0!==d),P:null})},a:function(a,b,c){function d(f){f>>=2;var m=F;return new e(ya,m[f+1],m[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ka:!0})},
i:function(a,b){b=I(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var e=F[d>>2];if(c)for(var f=d+4,m=0;m<=e;++m){var h=d+4+m;if(m==e||0==C[h]){if(f){var k=f;var l=C,n=k+(h-f);for(f=k;l[f]&&!(f>=n);)++f;if(16<f-k&&l.subarray&&oa)k=oa.decode(l.subarray(k,f));else{for(n="";k<f;){var p=l[k++];if(p&128){var u=l[k++]&63;if(192==(p&224))n+=String.fromCharCode((p&31)<<6|u);else{var v=l[k++]&63;p=224==(p&240)?(p&15)<<12|u<<6|v:(p&7)<<18|u<<12|v<<6|l[k++]&63;65536>p?n+=String.fromCharCode(p):
(p-=65536,n+=String.fromCharCode(55296|p>>10,56320|p&1023))}}else n+=String.fromCharCode(p)}k=n}}else k="";if(void 0===q)var q=k;else q+=String.fromCharCode(0),q+=k;f=h+1}}else{q=Array(e);for(m=0;m<e;++m)q[m]=String.fromCharCode(C[d+4+m]);q=q.join("")}X(d);return q},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||N("Cannot pass non-string to std::string");var m=(c&&
f?function(){for(var l=0,n=0;n<e.length;++n){var p=e.charCodeAt(n);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++n)&1023);127>=p?++l:l=2047>=p?l+2:65535>=p?l+3:l+4}return l}:function(){return e.length})(),h=Wb(4+m+1);F[h>>2]=m;if(c&&f)pa(e,h+4,m+1);else if(f)for(f=0;f<m;++f){var k=e.charCodeAt(f);255<k&&(X(h),N("String has UTF-16 code units that do not fit in 8 bits"));C[h+4+f]=k}else for(f=0;f<m;++f)C[h+4+f]=e[f];null!==d&&d.push(X,h);return h},argPackAdvance:8,readValueFromPointer:qb,
P:function(d){X(d)}})},f:function(a,b,c){c=I(c);if(2===b){var d=ra;var e=ta;var f=ua;var m=function(){return sa};var h=1}else 4===b&&(d=va,e=wa,f=xa,m=function(){return F},h=2);P(a,{name:c,fromWireType:function(k){for(var l=F[k>>2],n=m(),p,u=k+4,v=0;v<=l;++v){var q=k+4+v*b;if(v==l||0==n[q>>h])u=d(u,q-u),void 0===p?p=u:(p+=String.fromCharCode(0),p+=u),u=q+b}X(k);return p},toWireType:function(k,l){"string"!==typeof l&&N("Cannot pass non-string to C++ string type "+c);var n=f(l),p=Wb(4+n+b);F[p>>2]=
n>>h;e(l,p+4,n+b);null!==k&&k.push(X,p);return p},argPackAdvance:8,readValueFromPointer:qb,P:function(k){X(k)}})},t:function(a,b){b=I(b);P(a,{la:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},x:function(a,b,c){a=Lb(a);b=Mb(b,"emval::as");var d=[],e=U(d);E[c>>2]=e;return b.toWireType(d,a)},u:function(a,b,c,d){a=Pb[a];b=Lb(b);c=Ob(c);a(b,c,null,d)},c:Ib,n:function(a){if(0===a)return U(Qb());a=Ob(a);return U(Qb()[a])},v:function(a,b){b=Sb(a,b);for(var c=b[0],d=c.name+
"_$"+b.slice(1).map(function(l){return l.name}).join("_")+"$",e=["retType"],f=[c],m="",h=0;h<a-1;++h)m+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(b[1+h]);d="return function "+Va("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var k=0;for(h=0;h<a-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(k?"+"+k:"")+");\n",k+=b[h+1].argPackAdvance;d+="    var rv = handle[name]("+m+");\n";for(h=0;h<a-1;++h)b[h+1].deleteObject&&(d+="    argType"+h+".deleteObject(arg"+h+
");\n");c.la||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Fb(e).apply(null,f);return Rb(a)},k:function(a,b){a=Lb(a);b=Lb(b);return U(a[b])},d:function(a){4<a&&(Y[a].ba+=1)},m:function(a,b,c,d){a=Lb(a);var e=Tb[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var m="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)m+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+
f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",m+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Mb,g,U);Tb[b]=e}return e(a,c,d)},l:function(a){return U(Ob(a))},w:function(a){Eb(Y[a].value);Ib(a)},j:function(a,b){a=Mb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},g:function(){A()},o:function(a,b,c){C.copyWithin(a,b,b+c)},p:function(a){a>>>=
0;var b=C.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ma.grow(Math.min(2147483648,d)-ya.byteLength+65535>>>16);Ca();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}};
(function(){function a(e){g.asm=e.exports;ma=g.asm.A;Ca();Da=g.asm.C;G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);0==G&&(null!==Ka&&(clearInterval(Ka),Ka=null),La&&(e=La,La=null,e()))}function b(e){a(e.instance)}function c(e){return Qa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){ka("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:Xb};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return ka("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return la||"function"!==typeof WebAssembly.instantiateStreaming||Na()||Ma("file://")||"function"!==typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){ka("wasm streaming compile failed: "+f);ka("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ia=g.___wasm_call_ctors=function(){return(Ia=g.___wasm_call_ctors=g.asm.B).apply(null,arguments)},Bb=g.___getTypeName=function(){return(Bb=g.___getTypeName=g.asm.D).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.E).apply(null,arguments)};var Wb=g._malloc=function(){return(Wb=g._malloc=g.asm.F).apply(null,arguments)},X=g._free=function(){return(X=g._free=g.asm.G).apply(null,arguments)},Yb;
La=function Zb(){Yb||$b();Yb||(La=Zb)};
function $b(){function a(){if(!Yb&&(Yb=!0,g.calledRun=!0,!na)){Ra(Fa);Ra(Ga);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ha.unshift(b)}Ra(Ha)}}if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ja();Ra(Ea);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
g.run=$b;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();noExitRuntime=!0;$b();
