
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var ca={},m;for(m in h)h.hasOwnProperty(m)&&(ca[m]=h[m]);var da="./this.program",ea=!1,v=!1,fa=!1,ha=!1;ea="object"===typeof window;v="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!v;var y="",ia,ja,la,ma;
if(fa)y=v?require("path").dirname(y)+"/":__dirname+"/",ia=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",z),h.inspect=function(){return"[Emscripten Module object]"};
else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||v)v?y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(y=document.currentScript.src),y=
0!==y.indexOf("blob:")?y.substr(0,y.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var na=h.print||console.log.bind(console),C=h.printErr||console.warn.bind(console);for(m in ca)ca.hasOwnProperty(m)&&(h[m]=ca[m]);ca=null;h.thisProgram&&(da=h.thisProgram);var oa;h.wasmBinary&&(oa=h.wasmBinary);
var noExitRuntime;h.noExitRuntime&&(noExitRuntime=h.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var pa,qa=!1;function assert(a,b){a||z("Assertion failed: "+b)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function D(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function sa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function va(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&wa[c];)++c;c<<=1;if(32<c-a&&ua)return ua.decode(E.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=xa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ya(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)xa[b>>1]=a.charCodeAt(e),b+=2;xa[b>>1]=0;return b-d}function za(a){return 2*a.length}function Aa(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Da,G,E,xa,wa,F,H,Ea,Fa;
function Ga(){var a=pa.buffer;Da=a;h.HEAP8=G=new Int8Array(a);h.HEAP16=xa=new Int16Array(a);h.HEAP32=F=new Int32Array(a);h.HEAPU8=E=new Uint8Array(a);h.HEAPU16=wa=new Uint16Array(a);h.HEAPU32=H=new Uint32Array(a);h.HEAPF32=Ea=new Float32Array(a);h.HEAPF64=Fa=new Float64Array(a)}var Ha,Ia=[],Ja=[],Ka=[],La=[];function Ma(){var a=h.preRun.shift();Ia.unshift(a)}var I=0,Na=null,Oa=null;h.preloadedImages={};h.preloadedAudios={};
function z(a){if(h.onAbort)h.onAbort(a);C(a);qa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Pa(a){var b=J;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Qa(){return Pa("data:application/octet-stream;base64,")}var J="jpeg.wasm";if(!Qa()){var Ra=J;J=h.locateFile?h.locateFile(Ra,y):y+Ra}
function Sa(){var a=J;try{if(a==J&&oa)return new Uint8Array(oa);if(ja)return ja(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}function Ta(){return oa||!ea&&!v||"function"!==typeof fetch||Pa("file://")?Promise.resolve().then(function(){return Sa()}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Sa()})}var Ua,Va;
function Wa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.ab;"number"===typeof c?void 0===b.Ga?Ha.get(c)():Ha.get(c)(b.Ga):c(void 0===b.Ga?null:b.Ga)}}}function Xa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ya=void 0;function K(a){for(var b="";E[a];)b+=Ya[E[a++]];return b}var Za={},L={},$a={};
function ab(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function bb(a,b){a=ab(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function cb(a){var b=Error,c=bb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var db=void 0;function M(a){throw new db(a);}var eb=void 0;function fb(a){throw new eb(a);}
function N(a,b,c){function d(l){l=c(l);l.length!==a.length&&fb("Mismatched type converter count");for(var q=0;q<a.length;++q)O(a[q],l[q])}a.forEach(function(l){$a[l]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(l,q){L.hasOwnProperty(l)?e[q]=L[l]:(f.push(l),Za.hasOwnProperty(l)||(Za[l]=[]),Za[l].push(function(){e[q]=L[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function O(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||M('type "'+d+'" must have a positive integer typeid pointer');if(L.hasOwnProperty(a)){if(c.eb)return;M("Cannot register type '"+d+"' twice")}L[a]=b;delete $a[a];Za.hasOwnProperty(a)&&(b=Za[a],delete Za[a],b.forEach(function(e){e()}))}function gb(a){return{count:a.count,ra:a.ra,va:a.va,$:a.$,ba:a.ba,ea:a.ea,fa:a.fa}}
function hb(a){M(a.V.ba.Y.name+" instance already deleted")}var ib=!1;function jb(){}function kb(a){--a.count.value;0===a.count.value&&(a.ea?a.fa.qa(a.ea):a.ba.Y.qa(a.$))}function lb(a){if("undefined"===typeof FinalizationGroup)return lb=function(b){return b},a;ib=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.$?kb(c):console.warn("object already deleted: "+c.$)});lb=function(b){ib.register(b,b.V,b.V);return b};jb=function(b){ib.unregister(b.V)};return lb(a)}
var mb=void 0,nb=[];function ob(){for(;nb.length;){var a=nb.pop();a.V.ra=!1;a["delete"]()}}function Q(){}var pb={};function qb(a,b,c){if(void 0===a[b].ia){var d=a[b];a[b]=function(){a[b].ia.hasOwnProperty(arguments.length)||M("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].ia+")!");return a[b].ia[arguments.length].apply(this,arguments)};a[b].ia=[];a[b].ia[d.ya]=d}}
function rb(a,b){h.hasOwnProperty(a)?(M("Cannot register public name '"+a+"' twice"),qb(h,a,a),h.hasOwnProperty(void 0)&&M("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),h[a].ia[void 0]=b):h[a]=b}function sb(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.na=c;this.qa=d;this.ga=e;this.bb=f;this.xa=k;this.$a=l;this.jb=[]}
function tb(a,b,c){for(;b!==c;)b.xa||M("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.xa(a),b=b.ga;return a}function ub(a,b){if(null===b)return this.Ia&&M("null is not a valid "+this.name),0;b.V||M('Cannot pass "'+vb(b)+'" as a '+this.name);b.V.$||M("Cannot pass deleted object as a pointer of type "+this.name);return tb(b.V.$,b.V.ba.Y,this.Y)}
function wb(a,b){if(null===b){this.Ia&&M("null is not a valid "+this.name);if(this.Aa){var c=this.kb();null!==a&&a.push(this.qa,c);return c}return 0}b.V||M('Cannot pass "'+vb(b)+'" as a '+this.name);b.V.$||M("Cannot pass deleted object as a pointer of type "+this.name);!this.za&&b.V.ba.za&&M("Cannot convert argument of type "+(b.V.fa?b.V.fa.name:b.V.ba.name)+" to parameter type "+this.name);c=tb(b.V.$,b.V.ba.Y,this.Y);if(this.Aa)switch(void 0===b.V.ea&&M("Passing raw pointer to smart pointer is illegal"),
this.ob){case 0:b.V.fa===this?c=b.V.ea:M("Cannot convert argument of type "+(b.V.fa?b.V.fa.name:b.V.ba.name)+" to parameter type "+this.name);break;case 1:c=b.V.ea;break;case 2:if(b.V.fa===this)c=b.V.ea;else{var d=b.clone();c=this.lb(c,R(function(){d["delete"]()}));null!==a&&a.push(this.qa,c)}break;default:M("Unsupporting sharing policy")}return c}
function xb(a,b){if(null===b)return this.Ia&&M("null is not a valid "+this.name),0;b.V||M('Cannot pass "'+vb(b)+'" as a '+this.name);b.V.$||M("Cannot pass deleted object as a pointer of type "+this.name);b.V.ba.za&&M("Cannot convert argument of type "+b.V.ba.name+" to parameter type "+this.name);return tb(b.V.$,b.V.ba.Y,this.Y)}function yb(a){return this.fromWireType(H[a>>2])}function zb(a,b,c){if(b===c)return a;if(void 0===c.ga)return null;a=zb(a,b,c.ga);return null===a?null:c.$a(a)}var Ab={};
function Bb(a,b){for(void 0===b&&M("ptr should not be undefined");a.ga;)b=a.xa(b),a=a.ga;return Ab[b]}function Cb(a,b){b.ba&&b.$||fb("makeClassHandle requires ptr and ptrType");!!b.fa!==!!b.ea&&fb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return lb(Object.create(a,{V:{value:b}}))}
function S(a,b,c,d){this.name=a;this.Y=b;this.Ia=c;this.za=d;this.Aa=!1;this.qa=this.lb=this.kb=this.Wa=this.ob=this.ib=void 0;void 0!==b.ga?this.toWireType=wb:(this.toWireType=d?ub:xb,this.ka=null)}function Db(a,b){h.hasOwnProperty(a)||fb("Replacing nonexistant public symbol");h[a]=b;h[a].ya=void 0}
function Eb(a,b){assert(0<=a.indexOf("j"),"getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var e;-1!=a.indexOf("j")?e=c&&c.length?h["dynCall_"+a].apply(null,[b].concat(c)):h["dynCall_"+a].call(null,b):e=Ha.get(b).apply(null,c);return e}}function T(a,b){a=K(a);var c=-1!=a.indexOf("j")?Eb(a,b):Ha.get(b);"function"!==typeof c&&M("unknown function pointer with signature "+a+": "+b);return c}
var Fb=void 0;function Gb(a){a=Hb(a);var b=K(a);U(a);return b}function Ib(a,b){function c(f){e[f]||L[f]||($a[f]?$a[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Fb(a+": "+d.map(Gb).join([", "]));}function Jb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}function Kb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Lb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=bb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Mb(a,b,c){a instanceof Object||M(c+' with invalid "this": '+a);a instanceof b.Y.constructor||M(c+' incompatible with "this" of type '+a.constructor.name);a.V.$||M("cannot call emscripten binding method "+c+" on deleted object");return tb(a.V.$,a.V.ba.Y,b.Y)}var Nb=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ob(a){4<a&&0===--V[a].La&&(V[a]=void 0,Nb.push(a))}
function R(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Nb.length?Nb.pop():V.length;V[b]={La:1,value:a};return b}}function vb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Pb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ea[c>>2])};case 3:return function(c){return this.fromWireType(Fa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Qb(a,b,c){switch(b){case 0:return c?function(d){return G[d]}:function(d){return E[d]};case 1:return c?function(d){return xa[d>>1]}:function(d){return wa[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Rb(a){a||M("Cannot use deleted val. handle = "+a);return V[a].value}function Sb(a,b){var c=L[a];void 0===c&&M(b+" has unknown type "+Gb(a));return c}var Tb={};
function Ub(a){var b=Tb[a];return void 0===b?K(a):b}var Vb=[];function Wb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Xb(a){var b=Vb.length;Vb.push(a);return b}function Yb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Sb(F[(b>>2)+d],"parameter "+d);return c}var Zb={},$b={};
function ac(){if(!bc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in $b)a[b]=$b[b];var c=[];for(b in a)c.push(b+"="+a[b]);bc=c}return bc}var bc;
function cc(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function dc(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cc(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ec(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fc(a){if("/"===a)return"/";a=dc(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function hc(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function ic(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cc(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var jc=[];function kc(a,b){jc[a]={input:[],output:[],ta:b};lc(a,mc)}
var mc={open:function(a){var b=jc[a.node.rdev];if(!b)throw new W(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ta.flush(a.tty)},flush:function(a){a.tty.ta.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ta.Sa)throw new W(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.ta.Sa(a.tty)}catch(l){throw new W(29);}if(void 0===k&&0===e)throw new W(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.ta.Ja)throw new W(60);
try{for(var e=0;e<d;e++)a.tty.ta.Ja(a.tty,b[c+e])}catch(f){throw new W(29);}d&&(a.node.timestamp=Date.now());return e}},oc={Sa:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.Xa?Buffer.Xa(256):new Buffer(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nc(b,!0)}return a.input.shift()},Ja:function(a,b){null===b||10===b?(na(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(D(a.output,0)),a.output=[])}},pc={Ja:function(a,b){null===b||10===b?(C(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(C(D(a.output,0)),a.output=[])}},X={ha:null,la:function(){return X.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new W(63);X.ha||(X.ha={dir:{node:{ma:X.X.ma,ja:X.X.ja,lookup:X.X.lookup,Ba:X.X.Ba,rename:X.X.rename,unlink:X.X.unlink,rmdir:X.X.rmdir,readdir:X.X.readdir,symlink:X.X.symlink},stream:{pa:X.Z.pa}},file:{node:{ma:X.X.ma,ja:X.X.ja},stream:{pa:X.Z.pa,read:X.Z.read,write:X.Z.write,Ma:X.Z.Ma,Ta:X.Z.Ta,Va:X.Z.Va}},link:{node:{ma:X.X.ma,ja:X.X.ja,readlink:X.X.readlink},stream:{}},Na:{node:{ma:X.X.ma,ja:X.X.ja},stream:qc}});
c=rc(a,b,c,d);16384===(c.mode&61440)?(c.X=X.ha.dir.node,c.Z=X.ha.dir.stream,c.W={}):32768===(c.mode&61440)?(c.X=X.ha.file.node,c.Z=X.ha.file.stream,c.aa=0,c.W=null):40960===(c.mode&61440)?(c.X=X.ha.link.node,c.Z=X.ha.link.stream):8192===(c.mode&61440)&&(c.X=X.ha.Na.node,c.Z=X.ha.Na.stream);c.timestamp=Date.now();a&&(a.W[b]=c);return c},vb:function(a){if(a.W&&a.W.subarray){for(var b=[],c=0;c<a.aa;++c)b.push(a.W[c]);return b}return a.W},wb:function(a){return a.W?a.W.subarray?a.W.subarray(0,a.aa):new Uint8Array(a.W):
new Uint8Array(0)},Pa:function(a,b){var c=a.W?a.W.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.W,a.W=new Uint8Array(b),0<a.aa&&a.W.set(c.subarray(0,a.aa),0))},mb:function(a,b){if(a.aa!=b)if(0==b)a.W=null,a.aa=0;else{if(!a.W||a.W.subarray){var c=a.W;a.W=new Uint8Array(b);c&&a.W.set(c.subarray(0,Math.min(b,a.aa)))}else if(a.W||(a.W=[]),a.W.length>b)a.W.length=b;else for(;a.W.length<b;)a.W.push(0);a.aa=b}},X:{ma:function(a){var b={};b.dev=8192===(a.mode&61440)?
a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.aa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ya=4096;b.blocks=Math.ceil(b.size/b.Ya);return b},ja:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.mb(a,b.size)},lookup:function(){throw sc[44];},
Ba:function(a,b,c,d){return X.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=tc(b,c)}catch(f){}if(d)for(var e in d.W)throw new W(55);}delete a.parent.W[a.name];a.name=c;b.W[c]=a;a.parent=b},unlink:function(a,b){delete a.W[b]},rmdir:function(a,b){var c=tc(a,b),d;for(d in c.W)throw new W(55);delete a.W[b]},readdir:function(a){var b=[".",".."],c;for(c in a.W)a.W.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=X.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new W(28);return a.link}},Z:{read:function(a,b,c,d,e){var f=a.node.W;if(e>=a.node.aa)return 0;a=Math.min(a.node.aa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===G.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.W||a.W.subarray)){if(f)return a.W=b.subarray(c,c+d),a.aa=d;if(0===a.aa&&0===e)return a.W=b.slice(c,c+d),a.aa=d;if(e+
d<=a.aa)return a.W.set(b.subarray(c,c+d),e),d}X.Pa(a,e+d);if(a.W.subarray&&b.subarray)a.W.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.W[e+f]=b[c+f];a.aa=Math.max(a.aa,e+d);return d},pa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.aa);if(0>b)throw new W(28);return b},Ma:function(a,b,c){X.Pa(a.node,b+c);a.node.aa=Math.max(a.node.aa,b+c)},Ta:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new W(43);a=a.node.W;if(f&2||a.buffer!==Da){if(0<
d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=uc(f);c<f;)G[b+c++]=0;c=b;if(!c)throw new W(48);G.set(a,c)}else d=!1,c=a.byteOffset;return{$:c,ub:d}},Va:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new W(43);if(e&2)return 0;X.Z.write(a,b,0,d,c,!1);return 0}}},vc=null,wc={},xc=[],yc=1,zc=null,Ac=!0,Bc={},W=null,sc={};
function Y(a,b){a=ic("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ra:!0,Ka:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ka)throw new W(32);a=cc(a.split("/").filter(function(k){return!!k}),!1);var e=vc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=tc(e,a[d]);c=dc(c+"/"+a[d]);e.Ca&&(!f||f&&b.Ra)&&(e=e.Ca.root);if(!f||b.Qa)for(f=0;40960===(e.mode&61440);)if(e=Ec(c),c=ic(ec(c),e),e=Y(c,{Ka:b.Ka}).node,40<f++)throw new W(32);}return{path:c,node:e}}
function Fc(a){for(var b;;){if(a===a.parent)return a=a.la.Ua,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Gc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zc.length}function tc(a,b){var c;if(c=(c=Hc(a,"x"))?c:a.X.lookup?0:2)throw new W(c,a);for(c=zc[Gc(a.id,b)];c;c=c.hb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.X.lookup(a,b)}
function rc(a,b,c,d){a=new Ic(a,b,c,d);b=Gc(a.parent.id,a.name);a.hb=zc[b];return zc[b]=a}var Jc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Kc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hc(a,b){if(Ac)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lc(a,b){try{return tc(a,b),20}catch(c){}return Hc(a,"wx")}
function Mc(){var a=4096;for(var b=0;b<=a;b++)if(!xc[b])return b;throw new W(33);}function Nc(a){Oc||(Oc=function(){},Oc.prototype={});var b=new Oc,c;for(c in a)b[c]=a[c];a=b;b=Mc();a.fd=b;return xc[b]=a}var qc={open:function(a){a.Z=wc[a.node.rdev].Z;a.Z.open&&a.Z.open(a)},pa:function(){throw new W(70);}};function lc(a,b){wc[a]={Z:b}}
function Pc(a,b){var c="/"===b,d=!b;if(c&&vc)throw new W(10);if(!c&&!d){var e=Y(b,{Ra:!1});b=e.path;e=e.node;if(e.Ca)throw new W(10);if(16384!==(e.mode&61440))throw new W(54);}b={type:a,xb:{},Ua:b,gb:[]};a=a.la(b);a.la=b;b.root=a;c?vc=a:e&&(e.Ca=b,e.la&&e.la.gb.push(b))}function Qc(a,b,c){var d=Y(a,{parent:!0}).node;a=fc(a);if(!a||"."===a||".."===a)throw new W(28);var e=Lc(d,a);if(e)throw new W(e);if(!d.X.Ba)throw new W(63);return d.X.Ba(d,a,b,c)}function Z(a){Qc(a,16895,0)}
function Rc(a,b,c){"undefined"===typeof c&&(c=b,b=438);Qc(a,b|8192,c)}function Sc(a,b){if(!ic(a))throw new W(44);var c=Y(b,{parent:!0}).node;if(!c)throw new W(44);b=fc(b);var d=Lc(c,b);if(d)throw new W(d);if(!c.X.symlink)throw new W(63);c.X.symlink(c,b,a)}function Ec(a){a=Y(a).node;if(!a)throw new W(44);if(!a.X.readlink)throw new W(28);return ic(Fc(a.parent),a.X.readlink(a))}
function Tc(a,b){if(""===a)throw new W(44);if("string"===typeof b){var c=Jc[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=dc(a);try{e=Y(a,{Qa:!(b&131072)}).node}catch(k){}}c=!1;if(b&64)if(e){if(b&128)throw new W(20);}else e=Qc(a,d,0),c=!0;if(!e)throw new W(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new W(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Kc(b)||b&512)?31:Hc(e,Kc(b)):44))throw new W(d);if(b&512){d=e;var f;"string"===typeof d?f=Y(d,{Qa:!0}).node:f=d;if(!f.X.ja)throw new W(63);if(16384===(f.mode&61440))throw new W(31);if(32768!==(f.mode&61440))throw new W(28);if(d=Hc(f,"w"))throw new W(d);f.X.ja(f,{size:0,timestamp:Date.now()})}b&=-131713;e=Nc({node:e,path:Fc(e),flags:b,seekable:!0,position:0,Z:e.Z,tb:[],error:!1});e.Z.open&&e.Z.open(e);!h.logReadFiles||b&1||(Uc||(Uc={}),a in Uc||(Uc[a]=1,C("FS.trackingDelegate error on read file: "+
a)));try{Bc.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Bc.onOpenFile(a,e))}catch(k){C("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}}function Vc(a,b,c){if(null===a.fd)throw new W(8);if(!a.seekable||!a.Z.pa)throw new W(70);if(0!=c&&1!=c&&2!=c)throw new W(28);a.position=a.Z.pa(a,b,c);a.tb=[]}
function Wc(){W||(W=function(a,b){this.node=b;this.nb=function(c){this.sa=c};this.nb(a);this.message="FS error"},W.prototype=Error(),W.prototype.constructor=W,[44].forEach(function(a){sc[a]=new W(a);sc[a].stack="<generic error, no stack>"}))}var Xc;function Yc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Zc(a,b,c){a=dc("/dev/"+a);var d=Yc(!!b,!!c);$c||($c=64);var e=$c++<<8|0;lc(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,k,l,q){for(var p=0,r=0;r<q;r++){try{var x=b()}catch(w){throw new W(29);}if(void 0===x&&0===p)throw new W(6);if(null===x||void 0===x)break;p++;k[l+r]=x}p&&(f.node.timestamp=Date.now());return p},write:function(f,k,l,q){for(var p=0;p<q;p++)try{c(k[l+p])}catch(r){throw new W(29);}q&&(f.node.timestamp=Date.now());return p}});
Rc(a,d,e)}var $c,ad={},Oc,Uc;function bd(a){a=xc[a];if(!a)throw new W(8);return a}function cd(a){return 0===a%4&&(0!==a%100||0===a%400)}function dd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var ed=[31,29,31,30,31,30,31,31,30,31,30,31],fd=[31,28,31,30,31,30,31,31,30,31,30,31];
function gd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(cd(a.getFullYear())?ed:fd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function hd(a,b,c,d){function e(g,n,u){for(g="number"===typeof g?g.toString():g||"";g.length<n;)g=u[0]+g;return g}function f(g,n){return e(g,n,"0")}function k(g,n){function u(B){return 0>B?-1:0<B?1:0}var t;0===(t=u(g.getFullYear()-n.getFullYear()))&&0===(t=u(g.getMonth()-n.getMonth()))&&(t=u(g.getDate()-n.getDate()));return t}function l(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function q(g){g=gd(new Date(g.da+1900,0,1),g.Fa);var n=new Date(g.getFullYear()+1,0,4),u=l(new Date(g.getFullYear(),0,4));n=l(n);return 0>=k(u,g)?0>=k(n,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var p=F[d+40>>2];d={rb:F[d>>2],qb:F[d+4>>2],Da:F[d+8>>2],wa:F[d+12>>2],ua:F[d+16>>2],da:F[d+20>>2],Ea:F[d+24>>2],Fa:F[d+28>>2],yb:F[d+32>>2],pb:F[d+
36>>2],sb:p?p?D(E,p,void 0):"":""};c=c?D(E,c,void 0):"";p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in p)c=c.replace(new RegExp(r,"g"),p[r]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");p={"%a":function(g){return x[g.Ea].substring(0,3)},"%A":function(g){return x[g.Ea]},"%b":function(g){return w[g.ua].substring(0,3)},"%B":function(g){return w[g.ua]},"%C":function(g){return f((g.da+1900)/100|0,2)},"%d":function(g){return f(g.wa,2)},"%e":function(g){return e(g.wa,2," ")},"%g":function(g){return q(g).toString().substring(2)},"%G":function(g){return q(g)},"%H":function(g){return f(g.Da,
2)},"%I":function(g){g=g.Da;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":function(g){return f(g.wa+dd(cd(g.da+1900)?ed:fd,g.ua-1),3)},"%m":function(g){return f(g.ua+1,2)},"%M":function(g){return f(g.qb,2)},"%n":function(){return"\n"},"%p":function(g){return 0<=g.Da&&12>g.Da?"AM":"PM"},"%S":function(g){return f(g.rb,2)},"%t":function(){return"\t"},"%u":function(g){return g.Ea||7},"%U":function(g){var n=new Date(g.da+1900,0,1),u=0===n.getDay()?n:gd(n,7-n.getDay());g=new Date(g.da+1900,g.ua,g.wa);return 0>
k(u,g)?f(Math.ceil((31-u.getDate()+(dd(cd(g.getFullYear())?ed:fd,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(u,n)?"01":"00"},"%V":function(g){var n=new Date(g.da+1901,0,4),u=l(new Date(g.da+1900,0,4));n=l(n);var t=gd(new Date(g.da+1900,0,1),g.Fa);return 0>k(t,u)?"53":0>=k(n,t)?"01":f(Math.ceil((u.getFullYear()<g.da+1900?g.Fa+32-u.getDate():g.Fa+1-u.getDate())/7),2)},"%w":function(g){return g.Ea},"%W":function(g){var n=new Date(g.da,0,1),u=1===n.getDay()?n:gd(n,0===n.getDay()?1:7-n.getDay()+1);g=
new Date(g.da+1900,g.ua,g.wa);return 0>k(u,g)?f(Math.ceil((31-u.getDate()+(dd(cd(g.getFullYear())?ed:fd,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(u,n)?"01":"00"},"%y":function(g){return(g.da+1900).toString().substring(2)},"%Y":function(g){return g.da+1900},"%z":function(g){g=g.pb;var n=0<=g;g=Math.abs(g)/60;return(n?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.sb},"%%":function(){return"%"}};for(r in p)0<=c.indexOf(r)&&(c=c.replace(new RegExp(r,"g"),p[r](d)));r=
nc(c,!1);if(r.length>b)return 0;G.set(r,a);return r.length-1}for(var id=Array(256),jd=0;256>jd;++jd)id[jd]=String.fromCharCode(jd);Ya=id;db=h.BindingError=cb("BindingError");eb=h.InternalError=cb("InternalError");Q.prototype.isAliasOf=function(a){if(!(this instanceof Q&&a instanceof Q))return!1;var b=this.V.ba.Y,c=this.V.$,d=a.V.ba.Y;for(a=a.V.$;b.ga;)c=b.xa(c),b=b.ga;for(;d.ga;)a=d.xa(a),d=d.ga;return b===d&&c===a};
Q.prototype.clone=function(){this.V.$||hb(this);if(this.V.va)return this.V.count.value+=1,this;var a=lb(Object.create(Object.getPrototypeOf(this),{V:{value:gb(this.V)}}));a.V.count.value+=1;a.V.ra=!1;return a};Q.prototype["delete"]=function(){this.V.$||hb(this);this.V.ra&&!this.V.va&&M("Object already scheduled for deletion");jb(this);kb(this.V);this.V.va||(this.V.ea=void 0,this.V.$=void 0)};Q.prototype.isDeleted=function(){return!this.V.$};
Q.prototype.deleteLater=function(){this.V.$||hb(this);this.V.ra&&!this.V.va&&M("Object already scheduled for deletion");nb.push(this);1===nb.length&&mb&&mb(ob);this.V.ra=!0;return this};S.prototype.cb=function(a){this.Wa&&(a=this.Wa(a));return a};S.prototype.Oa=function(a){this.qa&&this.qa(a)};S.prototype.argPackAdvance=8;S.prototype.readValueFromPointer=yb;S.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
S.prototype.fromWireType=function(a){function b(){return this.Aa?Cb(this.Y.na,{ba:this.ib,$:c,fa:this,ea:a}):Cb(this.Y.na,{ba:this,$:a})}var c=this.cb(a);if(!c)return this.Oa(a),null;var d=Bb(this.Y,c);if(void 0!==d){if(0===d.V.count.value)return d.V.$=c,d.V.ea=a,d.clone();d=d.clone();this.Oa(a);return d}d=this.Y.bb(c);d=pb[d];if(!d)return b.call(this);d=this.za?d.Za:d.pointerType;var e=zb(c,this.Y,d.Y);return null===e?b.call(this):this.Aa?Cb(d.Y.na,{ba:d,$:e,fa:this,ea:a}):Cb(d.Y.na,{ba:d,$:e})};
h.getInheritedInstanceCount=function(){return Object.keys(Ab).length};h.getLiveInheritedInstances=function(){var a=[],b;for(b in Ab)Ab.hasOwnProperty(b)&&a.push(Ab[b]);return a};h.flushPendingDeletes=ob;h.setDelayFunction=function(a){mb=a;nb.length&&mb&&mb(ob)};Fb=h.UnboundTypeError=cb("UnboundTypeError");h.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};
function Ic(a,b,c,d){a||(a=this);this.parent=a;this.la=a.la;this.Ca=null;this.id=yc++;this.name=b;this.mode=c;this.X={};this.Z={};this.rdev=d}Object.defineProperties(Ic.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Wc();zc=Array(4096);Pc(X,"/");Z("/tmp");Z("/home");Z("/home/web_user");
(function(){Z("/dev");lc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Rc("/dev/null",259);kc(1280,oc);kc(1536,pc);Rc("/dev/tty",1280);Rc("/dev/tty1",1536);var a=hc();Zc("random",a);Zc("urandom",a);Z("/dev/shm");Z("/dev/shm/tmp")})();Z("/proc");Z("/proc/self");Z("/proc/self/fd");
Pc({la:function(){var a=rc("/proc/self","fd",16895,73);a.X={lookup:function(b,c){var d=xc[+c];if(!d)throw new W(8);b={parent:null,la:{Ua:"fake"},X:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");function nc(a,b){var c=Array(ta(a)+1);a=sa(a,c,0,c.length);b&&(c.length=a);return c}Ja.push({ab:function(){kd()}});
var ld={A:function(a,b,c,d,e){var f=Xa(c);b=K(b);O(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=G;else if(2===c)l=xa;else if(4===c)l=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>f])},ka:null})},I:function(a,b,c,d,e,f,k,l,q,p,r,x,w){r=K(r);f=T(e,f);l&&(l=T(k,l));p&&(p=T(q,p));w=T(x,w);var g=ab(r);rb(g,function(){Ib("Cannot construct "+r+" due to unbound types",
[d])});N([a,b,c],d?[d]:[],function(n){n=n[0];if(d){var u=n.Y;var t=u.na}else t=Q.prototype;n=bb(g,function(){if(Object.getPrototypeOf(this)!==B)throw new db("Use 'new' to construct "+r);if(void 0===A.oa)throw new db(r+" has no accessible constructor");var aa=A.oa[arguments.length];if(void 0===aa)throw new db("Tried to invoke ctor of "+r+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(A.oa).toString()+") parameters instead!");return aa.apply(this,arguments)});var B=
Object.create(t,{constructor:{value:n}});n.prototype=B;var A=new sb(r,n,B,w,u,f,l,p);u=new S(r,A,!0,!1);t=new S(r+"*",A,!1,!1);var P=new S(r+" const*",A,!1,!0);pb[a]={pointerType:t,Za:P};Db(g,n);return[u,t,P]})},H:function(a,b,c,d,e,f){assert(0<b);var k=Jb(b,c);e=T(d,e);var l=[f],q=[];N([],[a],function(p){p=p[0];var r="constructor "+p.name;void 0===p.Y.oa&&(p.Y.oa=[]);if(void 0!==p.Y.oa[b-1])throw new db("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+
p.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");p.Y.oa[b-1]=function(){Ib("Cannot construct "+p.name+" due to unbound types",k)};N([],k,function(x){p.Y.oa[b-1]=function(){arguments.length!==b-1&&M(r+" called with "+arguments.length+" arguments, expected "+(b-1));q.length=0;l.length=b;for(var w=1;w<b;++w)l[w]=x[w].toWireType(q,arguments[w-1]);w=e.apply(null,l);Kb(q);return x[0].fromWireType(w)};return[]});return[]})},z:function(a,b,c,d,
e,f,k,l){var q=Jb(c,d);b=K(b);f=T(e,f);N([],[a],function(p){function r(){Ib("Cannot call "+x+" due to unbound types",q)}p=p[0];var x=p.name+"."+b;l&&p.Y.jb.push(b);var w=p.Y.na,g=w[b];void 0===g||void 0===g.ia&&g.className!==p.name&&g.ya===c-2?(r.ya=c-2,r.className=p.name,w[b]=r):(qb(w,b,x),w[b].ia[c-2]=r);N([],q,function(n){var u=x,t=p,B=f,A=n.length;2>A&&M("argTypes array size mismatch! Must at least get return value and 'this' types!");var P=null!==n[1]&&null!==t,aa=!1;for(t=1;t<n.length;++t)if(null!==
n[t]&&void 0===n[t].ka){aa=!0;break}var Cc="void"!==n[0].name,ba="",ka="";for(t=0;t<A-2;++t)ba+=(0!==t?", ":"")+"arg"+t,ka+=(0!==t?", ":"")+"arg"+t+"Wired";u="return function "+ab(u)+"("+ba+") {\nif (arguments.length !== "+(A-2)+") {\nthrowBindingError('function "+u+" called with ' + arguments.length + ' arguments, expected "+(A-2)+" args!');\n}\n";aa&&(u+="var destructors = [];\n");var Dc=aa?"destructors":"null";ba="throwBindingError invoker fn runDestructors retType classParam".split(" ");B=[M,
B,k,Kb,n[0],n[1]];P&&(u+="var thisWired = classParam.toWireType("+Dc+", this);\n");for(t=0;t<A-2;++t)u+="var arg"+t+"Wired = argType"+t+".toWireType("+Dc+", arg"+t+"); // "+n[t+2].name+"\n",ba.push("argType"+t),B.push(n[t+2]);P&&(ka="thisWired"+(0<ka.length?", ":"")+ka);u+=(Cc?"var rv = ":"")+"invoker(fn"+(0<ka.length?", ":"")+ka+");\n";if(aa)u+="runDestructors(destructors);\n";else for(t=P?1:2;t<n.length;++t)A=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==n[t].ka&&(u+=A+"_dtor("+A+"); // "+n[t].name+
"\n",ba.push(A+"_dtor"),B.push(n[t].ka));Cc&&(u+="var ret = retType.fromWireType(rv);\nreturn ret;\n");ba.push(u+"}\n");n=Lb(ba).apply(null,B);void 0===w[b].ia?(n.ya=c-2,w[b]=n):w[b].ia[c-2]=n;return[]});return[]})},e:function(a,b,c,d,e,f,k,l,q,p){b=K(b);e=T(d,e);N([],[a],function(r){r=r[0];var x=r.name+"."+b,w={get:function(){Ib("Cannot access "+x+" due to unbound types",[c,k])},enumerable:!0,configurable:!0};q?w.set=function(){Ib("Cannot access "+x+" due to unbound types",[c,k])}:w.set=function(){M(x+
" is a read-only property")};Object.defineProperty(r.Y.na,b,w);N([],q?[c,k]:[c],function(g){var n=g[0],u={get:function(){var B=Mb(this,r,x+" getter");return n.fromWireType(e(f,B))},enumerable:!0};if(q){q=T(l,q);var t=g[1];u.set=function(B){var A=Mb(this,r,x+" setter"),P=[];q(p,A,t.toWireType(P,B));Kb(P)}}Object.defineProperty(r.Y.na,b,u);return[]});return[]})},y:function(a,b){b=K(b);O(a,{name:b,fromWireType:function(c){var d=V[c].value;Ob(c);return d},toWireType:function(c,d){return R(d)},argPackAdvance:8,
readValueFromPointer:yb,ka:null})},k:function(a,b,c){c=Xa(c);b=K(b);O(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+vb(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Pb(b,c),ka:null})},b:function(a,b,c,d,e){function f(p){return p}b=K(b);-1===e&&(e=4294967295);var k=Xa(c);if(0===d){var l=32-8*c;f=function(p){return p<<l>>>l}}var q=-1!=b.indexOf("unsigned");O(a,{name:b,
fromWireType:f,toWireType:function(p,r){if("number"!==typeof r&&"boolean"!==typeof r)throw new TypeError('Cannot convert "'+vb(r)+'" to '+this.name);if(r<d||r>e)throw new TypeError('Passing a number "'+vb(r)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return q?r>>>0:r|0},argPackAdvance:8,readValueFromPointer:Qb(b,k,0!==d),ka:null})},a:function(a,b,c){function d(f){f>>=2;var k=H;return new e(Da,k[f+1],k[f])}var e=[Int8Array,Uint8Array,
Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);O(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{eb:!0})},l:function(a,b){b=K(b);var c="std::string"===b;O(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var l=d+4+k;if(k==e||0==E[l]){f=f?D(E,f,l-f):"";if(void 0===q)var q=f;else q+=String.fromCharCode(0),q+=f;f=l+1}}else{q=Array(e);for(k=0;k<e;++k)q[k]=String.fromCharCode(E[d+4+k]);q=q.join("")}U(d);return q},toWireType:function(d,
e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||M("Cannot pass non-string to std::string");var k=(c&&f?function(){return ta(e)}:function(){return e.length})(),l=uc(4+k+1);H[l>>2]=k;if(c&&f)sa(e,E,l+4,k+1);else if(f)for(f=0;f<k;++f){var q=e.charCodeAt(f);255<q&&(U(l),M("String has UTF-16 code units that do not fit in 8 bits"));E[l+4+f]=q}else for(f=0;f<k;++f)E[l+4+f]=e[f];null!==d&&d.push(U,
l);return l},argPackAdvance:8,readValueFromPointer:yb,ka:function(d){U(d)}})},f:function(a,b,c){c=K(c);if(2===b){var d=va;var e=ya;var f=za;var k=function(){return wa};var l=1}else 4===b&&(d=Aa,e=Ba,f=Ca,k=function(){return H},l=2);O(a,{name:c,fromWireType:function(q){for(var p=H[q>>2],r=k(),x,w=q+4,g=0;g<=p;++g){var n=q+4+g*b;if(g==p||0==r[n>>l])w=d(w,n-w),void 0===x?x=w:(x+=String.fromCharCode(0),x+=w),w=n+b}U(q);return x},toWireType:function(q,p){"string"!==typeof p&&M("Cannot pass non-string to C++ string type "+
c);var r=f(p),x=uc(4+r+b);H[x>>2]=r>>l;e(p,x+4,r+b);null!==q&&q.push(U,x);return x},argPackAdvance:8,readValueFromPointer:yb,ka:function(q){U(q)}})},B:function(a,b){b=K(b);O(a,{fb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},h:function(a,b,c){a=Rb(a);b=Sb(b,"emval::as");var d=[],e=R(d);F[c>>2]=e;return b.toWireType(d,a)},C:function(a,b,c,d){a=Vb[a];b=Rb(b);c=Ub(c);a(b,c,null,d)},c:Ob,n:function(a){if(0===a)return R(Wb());a=Ub(a);return R(Wb()[a])},D:function(a,b){b=
Yb(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+"$",e=["retType"],f=[c],k="",l=0;l<a-1;++l)k+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+ab("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var q=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(q?"+"+q:"")+");\n",q+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+k+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+
l+".deleteObject(arg"+l+");\n");c.fb||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Lb(e).apply(null,f);return Xb(a)},E:function(a,b){a=Rb(a);b=Rb(b);return R(a[b])},d:function(a){4<a&&(V[a].La+=1)},G:function(a,b,c,d){a=Rb(a);var e=Zb[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)k+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Sb,h,R);Zb[b]=e}return e(a,c,d)},F:function(a){return R(Ub(a))},g:function(a){Kb(V[a].value);Ob(a)},m:function(a,b){a=Sb(a,"_emval_take_value");a=a.readValueFromPointer(b);return R(a)},o:function(a){a=Rb(a);return R(typeof a)},j:function(){z()},
r:function(a,b,c){E.copyWithin(a,b,b+c)},s:function(a){a>>>=0;var b=E.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{pa.grow(Math.min(2147483648,d)-Da.byteLength+65535>>>16);Ga();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},u:function(a,b){try{var c=0;ac().forEach(function(d,e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)G[e++>>0]=d.charCodeAt(f);G[e>>0]=0;c+=d.length+
1});return 0}catch(d){return"undefined"!==typeof ad&&d instanceof W||z(d),d.sa}},v:function(a,b){try{var c=ac();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0}catch(e){return"undefined"!==typeof ad&&e instanceof W||z(e),e.sa}},x:function(a){try{var b=bd(a);if(null===b.fd)throw new W(8);b.Ha&&(b.Ha=null);try{b.Z.close&&b.Z.close(b)}catch(c){throw c;}finally{xc[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof ad&&c instanceof W||z(c),c.sa}},w:function(a,
b,c,d){try{a:{for(var e=bd(a),f=a=0;f<c;f++){var k=F[b+(8*f+4)>>2],l=e,q=F[b+8*f>>2],p=k,r=void 0,x=G;if(0>p||0>r)throw new W(28);if(null===l.fd)throw new W(8);if(1===(l.flags&2097155))throw new W(8);if(16384===(l.node.mode&61440))throw new W(31);if(!l.Z.read)throw new W(28);var w="undefined"!==typeof r;if(!w)r=l.position;else if(!l.seekable)throw new W(70);var g=l.Z.read(l,x,q,p,r);w||(l.position+=g);var n=g;if(0>n){var u=-1;break a}a+=n;if(n<k)break}u=a}F[d>>2]=u;return 0}catch(t){return"undefined"!==
typeof ad&&t instanceof W||z(t),t.sa}},p:function(a,b,c,d,e){try{var f=bd(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Vc(f,a,d);Va=[f.position>>>0,(Ua=f.position,1<=+Math.abs(Ua)?0<Ua?(Math.min(+Math.floor(Ua/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Ua-+(~~Ua>>>0))/4294967296)>>>0:0)];F[e>>2]=Va[0];F[e+4>>2]=Va[1];f.Ha&&0===a&&0===d&&(f.Ha=null);return 0}catch(k){return"undefined"!==typeof ad&&k instanceof W||z(k),k.sa}},i:function(a,b,c,d){try{a:{for(var e=
bd(a),f=a=0;f<c;f++){var k=e,l=F[b+8*f>>2],q=F[b+(8*f+4)>>2],p=void 0,r=G;if(0>q||0>p)throw new W(28);if(null===k.fd)throw new W(8);if(0===(k.flags&2097155))throw new W(8);if(16384===(k.node.mode&61440))throw new W(31);if(!k.Z.write)throw new W(28);k.seekable&&k.flags&1024&&Vc(k,0,2);var x="undefined"!==typeof p;if(!x)p=k.position;else if(!k.seekable)throw new W(70);var w=k.Z.write(k,r,l,q,p,void 0);x||(k.position+=w);try{if(k.path&&Bc.onWriteToFile)Bc.onWriteToFile(k.path)}catch(u){C("FS.trackingDelegate['onWriteToFile']('"+
k.path+"') threw an exception: "+u.message)}var g=w;if(0>g){var n=-1;break a}a+=g}n=a}F[d>>2]=n;return 0}catch(u){return"undefined"!==typeof ad&&u instanceof W||z(u),u.sa}},q:function(){},t:function(a,b,c,d){return hd(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;pa=h.asm.J;Ga();Ha=h.asm.K;I--;h.monitorRunDependencies&&h.monitorRunDependencies(I);0==I&&(null!==Na&&(clearInterval(Na),Na=null),Oa&&(e=Oa,Oa=null,e()))}function b(e){a(e.instance)}function c(e){return Ta().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){C("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:ld};I++;h.monitorRunDependencies&&h.monitorRunDependencies(I);if(h.instantiateWasm)try{return h.instantiateWasm(d,
a)}catch(e){return C("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return oa||"function"!==typeof WebAssembly.instantiateStreaming||Qa()||Pa("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){C("wasm streaming compile failed: "+f);C("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var kd=h.___wasm_call_ctors=function(){return(kd=h.___wasm_call_ctors=h.asm.L).apply(null,arguments)},Hb=h.___getTypeName=function(){return(Hb=h.___getTypeName=h.asm.M).apply(null,arguments)};h.___embind_register_native_and_builtin_types=function(){return(h.___embind_register_native_and_builtin_types=h.asm.N).apply(null,arguments)};var uc=h._malloc=function(){return(uc=h._malloc=h.asm.O).apply(null,arguments)},U=h._free=function(){return(U=h._free=h.asm.P).apply(null,arguments)};
h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.Q).apply(null,arguments)};h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.R).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.S).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.T).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.U).apply(null,arguments)};var md;Oa=function nd(){md||od();md||(Oa=nd)};
function od(){function a(){if(!md&&(md=!0,h.calledRun=!0,!qa)){h.noFSInit||Xc||(Xc=!0,Wc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Zc("stdin",h.stdin):Sc("/dev/tty","/dev/stdin"),h.stdout?Zc("stdout",null,h.stdout):Sc("/dev/tty","/dev/stdout"),h.stderr?Zc("stderr",null,h.stderr):Sc("/dev/tty1","/dev/stderr"),Tc("/dev/stdin",0),Tc("/dev/stdout",1),Tc("/dev/stderr",1));Wa(Ja);Ac=!1;Wa(Ka);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();La.unshift(b)}Wa(La)}}if(!(0<I)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ma();Wa(Ia);0<I||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}h.run=od;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();noExitRuntime=!0;od();
